In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

This dataset is designed to simulate data for modeling an intelligent system that provides personalized diet recommendations based on individual health profiles, dietary needs, and medical conditions. The data integrates various patient attributes such as demographic details, medical history, dietary preferences, and health indicators, making it suitable for machine learning tasks in healthcare and nutrition management.

Dataset Description
- Rows (Observations): 1000
- Columns (Features): 17
- Target Column: Diet_Recommendation
Key Features
Feature Name Description
- Patient_ID Unique identifier for each patient.
- Age Age of the patient.
- Gender Gender of the patient (Male, Female).
- Weight_kg Weight of the patient in kilograms.
- Height_cm Height of the patient in centimeters.
- BMI Body Mass Index calculated as Weight (kg) / (Height (m)^2).
- Disease_Type Primary disease diagnosed (Diabetes, Hypertension, Obesity, or None).
- Severity Severity of the disease (Mild, Moderate, Severe).
- Physical_Activity_Level Level of physical activity (Sedentary, Moderate, Active).
- Daily_Caloric_Intake Average daily calorie consumption.
- Cholesterol_mg/dL Cholesterol level in mg/dL.
- Blood_Pressure_mmHg Average blood pressure in mmHg.
- Glucose_mg/dL Blood glucose level in mg/dL.
- Dietary_Restrictions Known dietary restrictions (Low_Sodium, Low_Sugar, None).
- Allergies Known food allergies (Peanuts, Gluten, None).
- Preferred_Cuisine Patient's preferred cuisine (Indian, Italian, Chinese, Mexican).
- Weekly_Exercise_Hours Number of hours exercised per week.
- Adherence_to_Diet_Plan Patient's adherence to a suggested diet plan (percentage).
- Dietary_Nutrient_Imbalance_Score A score indicating nutrient imbalance in the patient's diet.


Target Column

Diet_Recommendation: Suggested dietary plan based on individual health conditions:
- Low_Carb: For managing diabetes or weight-related concerns.
- Low_Sodium: For hypertension or cardiovascular health.
- Balanced: For general health improvement or non-specific requirements.

In [2]:
data = pd.read_csv('data/users.csv')
data.head()

,Patient_ID,Age,Gender,Weight_kg,Height_cm,BMI,Disease_Type,Severity,Physical_Activity_Level,Daily_Caloric_Intake,Cholesterol_mg/dL,Blood_Pressure_mmHg,Glucose_mg/dL,Dietary_Restrictions,Allergies,Preferred_Cuisine,Weekly_Exercise_Hours,Adherence_to_Diet_Plan,Dietary_Nutrient_Imbalance_Score,Diet_Recommendation
0,P0001,56,Male,58.4,160,22.8,Obesity,Moderate,Moderate,3079,173.3,133,116.3,NaN,Peanuts,Mexican,3.1,96.6,3.1,Balanced
1,P0002,69,Male,101.2,169,35.4,Diabetes,Mild,Moderate,3032,199.2,120,137.1,NaN,Peanuts,Chinese,4.5,63.2,0.6,Low_Carb
2,P0003,46,Female,63.5,173,21.2,Hypertension,Mild,Sedentary,1737,181.0,121,109.6,NaN,Peanuts,Chinese,3.8,57.5,4.6,Low_Sodium
3,P0004,32,Male,58.1,164,21.6,NaN,Mild,Moderate,2657,168.2,144,159.4,NaN,NaN,Mexican,4.3,54.5,0.4,Balanced
4,P0005,60,Male,79.5,197,20.5,Diabetes,Moderate,Sedentary,3496,200.4,172,182.3,Low_Sugar,NaN,Italian,9.8,78.2,4.7,Low_Carb

This dataframe has 1000 rows & 20 columns. Out of which `Patient_ID`, `Gender`, `Severity`, `Disease_Type`, `Physical_Activity_Level`, `Dietary_Restrictions`, `Allergies`, `Preferred_Cuisine` & `Diet_Recommendation` are categorical variables. The rest are numerical variables.

In [3]:
data.columns

Index(['Patient_ID', 'Age', 'Gender', 'Weight_kg', 'Height_cm', 'BMI',
       'Disease_Type', 'Severity', 'Physical_Activity_Level',
       'Daily_Caloric_Intake', 'Cholesterol_mg/dL', 'Blood_Pressure_mmHg',
       'Glucose_mg/dL', 'Dietary_Restrictions', 'Allergies',
       'Preferred_Cuisine', 'Weekly_Exercise_Hours', 'Adherence_to_Diet_Plan',
       'Dietary_Nutrient_Imbalance_Score', 'Diet_Recommendation'],
      dtype='object')

In [4]:
pd.set_option('display.max_colwidth', None)
data.describe()

,Age,Weight_kg,Height_cm,BMI,Daily_Caloric_Intake,Cholesterol_mg/dL,Blood_Pressure_mmHg,Glucose_mg/dL,Weekly_Exercise_Hours,Adherence_to_Diet_Plan,Dietary_Nutrient_Imbalance_Score
count,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000
mean,49.857000,84.602400,174.81700,28.191600,2475.064000,199.717900,144.993000,136.867600,5.166000,74.88430,2.469200
std,18.114267,20.088121,14.33377,8.040136,565.017032,29.080614,20.245712,37.934819,2.847995,14.82638,1.459631
min,18.000000,50.000000,150.00000,13.000000,1500.000000,150.400000,110.000000,70.200000,0.000000,50.00000,0.000000
25%,35.000000,66.600000,162.00000,22.075000,1984.750000,174.300000,128.000000,105.000000,2.800000,62.00000,1.200000
50%,50.000000,85.200000,175.00000,27.450000,2470.500000,199.850000,145.000000,138.000000,5.200000,74.20000,2.400000
75%,66.000000,102.000000,187.00000,33.425000,2937.250000,224.850000,163.000000,170.650000,7.600000,88.20000,3.700000
max,79.000000,119.700000,199.00000,52.400000,3498.000000,249.900000,179.000000,200.000000,10.000000,100.00000,5.000000

There are three types of diseases our users have in this dataset i.e. **Obesity** , **Diabetes** & **Hypertension**. There  is another column, `Severity` which consists the severity of the disease user is having. In this column, there are three types of severity i.e. **Mild** , **Moderate** & **Severe**; interesting part is that there are values for disease type consisting null values. We will have to handle these null values.

In [5]:
data.isna().sum()

Patient_ID                            0
Age                                   0
Gender                                0
Weight_kg                             0
Height_cm                             0
BMI                                   0
Disease_Type                        204
Severity                              0
Physical_Activity_Level               0
Daily_Caloric_Intake                  0
Cholesterol_mg/dL                     0
Blood_Pressure_mmHg                   0
Glucose_mg/dL                         0
Dietary_Restrictions                334
Allergies                           323
Preferred_Cuisine                     0
Weekly_Exercise_Hours                 0
Adherence_to_Diet_Plan                0
Dietary_Nutrient_Imbalance_Score      0
Diet_Recommendation                   0
dtype: int64

### Create derived features

The BMI values are categorised based on values given in the Centre of Disease Control website. We created two new features called `BMI_Category` which is a categorical variable that categorises the BMI values into **Underweight**, **Normal weight**, **Overweight**, and **Obese**. The second feature is `Caloric_Needs` which is a numerical variable that calculates the caloric needs based on the **Revised Harris-Benedict Equation**.

The Revised Harris-Benedict Equation is a widely used method to estimate daily calorie needs based on age, gender, weight, height, and activity level. This equation was developed in the 1910s by Dr. James Harris and Dr. Francis Benedict and has been revised over the years to account for changes in lifestyle and dietary habits.

The Revised Harris-Benedict Equation takes into consideration the basal metabolic rate (BMR), which is the number of calories the body needs to maintain basic functions such as breathing and circulation, and the physical activity level (PAL), which is the amount of energy expended during daily activities.

The formula for the Revised Harris-Benedict Equation is:

For men: BMR = 13.397 * weight(in kgs) + 4.799 * height(in cms) − 5.677 * age(in yrs) + 88.362

For women: BMR = 9.247 * weight(in kgs) + 3.098 * height(in cms) − 4.33 * age(in yrs) + 447.593

Once you have calculated the BMR using the appropriate formula, you can determine the daily calorie needs by multiplying the BMR by the appropriate physical activity level (PAL) factor:

- Sedentary : BMR x 1.2
- Moderate : BMR x 1.55
- Active : BMR x 1.9

In [7]:
# BMI Category
def get_bmi_category(bmi):
    if bmi < 18.5:
        return 'Underweight'
    elif 18.5 <= bmi < 25:
        return 'Normalweight'
    elif 25 <= bmi < 30:
        return 'Overweight'
    else:
        return 'Obese'

data['BMI_Category'] = data['BMI'].apply(get_bmi_category)

# Caloric Needs (Harris-Benedict Equation)
def calculate_caloric_needs(row):
    if row['Gender'] == 'Male':
        bmr = 88.362 + (13.397 * row['Weight_kg']) + (4.799 * row['Height_cm']) - (5.677 * row['Age'])
    else:
        bmr = 447.593 + (9.247 * row['Weight_kg']) + (3.098 * row['Height_cm']) - (4.330 * row['Age'])
    
    if row['Physical_Activity_Level'] == 'Sedentary':
        return bmr * 1.2
    elif row['Physical_Activity_Level'] == 'Moderate':
        return bmr * 1.55
    else:
        return bmr * 1.9

data['Caloric_Needs'] = data.apply(calculate_caloric_needs, axis=1)

### Encode categorical variables

In [8]:
from sklearn.preprocessing import LabelEncoder

df = pd.get_dummies(data, columns=['Gender', 'Disease_Type', 'Preferred_Cuisine', 'Allergies'])

label_encoder = LabelEncoder()
df['BMI_Category'] = label_encoder.fit_transform(df['BMI_Category'])
df['Severity'] = label_encoder.fit_transform(df['Severity'])
df['Physical_Activity_Level'] = label_encoder.fit_transform(df['Physical_Activity_Level'])
df['Dietary_Restrictions'] = label_encoder.fit_transform(df['Dietary_Restrictions'])

### Normalize numerical variables

In [9]:
from sklearn.preprocessing import StandardScaler

numerical_cols = ['Age', 'Weight_kg', 'Height_cm', 'Cholesterol_mg/dL', 
                  'Blood_Pressure_mmHg', 'Glucose_mg/dL', 'Daily_Caloric_Intake', 'Caloric_Needs', 
                  'Weekly_Exercise_Hours', 'Adherence_to_Diet_Plan', 'Dietary_Nutrient_Imbalance_Score']

scaler = StandardScaler()
df[numerical_cols] = scaler.fit_transform(df[numerical_cols])